name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --configuration Release --output ./Release -r win-x64 -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:PublishTrimmed=True -p:DebugType=None --self-contained      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: LighthouseManager-win10-64
        path: |
          Release/LighthouseManager.exe
          Release/SteamVRWatcher.exe
          Release/appsettings.json
 
